### ISSUE TITLE
iothub-explorer device-method and azure-iot-sdk-c serializer

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/iothub-explorer#16] opened 2017-04-12 05:43 UTC
Azure-iot-sdk-c serializer sample([1](https://github.com/Azure/azure-iot-sdk-c/blob/master/serializer/samples/simplesample_mqtt/simplesample_mqtt.c#L39)) has direct-methods likes `TurnFanOn`. But I am not able to invoke those methods with iothub-explorer. After login, I tried below 
```
$ iothub-explorer send deviceName TurnFanOn 
$ iothub-explorer device-method deviceName TurnFanOn
```
First command resulted in a error message related to JSON at device side and second didn't work. How to invoke direct-methods using iothub-explorer ? This issue with direct-methods happens only on client implemented using azure-iot-sdk-c serializer library. When the client is implemented using azure-iot-sdk-node library([2](https://github.com/Azure/azure-iot-sdk-node/blob/master/device/samples/device_methods.js)), device-methods at device side are invoked correctly.

I couldn't find a developer mailing list and so posted in github issues. Please let me know mailing list if any.

**Comment by pierreca** [comment] 2017-04-12 18:48
Can you let us know what version of iothub-explorer you're using? I checked in some changes to the payload handling of device methods 2 days ago. 
```
$ iothub-explorer --version
```

**Comment by kiranpradeep** [comment] 2017-04-13 08:02
@pierreca Copying the terminal
```
$:~/node/iothub-explorer-master$ nodejs -v
v7.8.0
$:~/node/iothub-explorer-master$ iothub-explorer --version
1.1.11
$:~/node/iothub-explorer-master$ iothub-explorer device-method deviceName TurnFanOn
Error: GatewayTimeoutError: Timed out waiting for the response from device.
```
I also tried cloning master and executing directly with same results.
```
$:~/node/iothub-explorer-master$ nodejs iothub-explorer-device-method.js deviceName TurnFanOn
Error: GatewayTimeoutError: Timed out waiting for the response from device.
```

**Comment by peterdn** [comment] 2017-04-13 21:12
The failure of the `iothub-explorer send` command is probably related to this issue in azure-iot-sdk-c: https://github.com/Azure/azure-iot-sdk-c/issues/116

iothub-explorer creates a new message with a UUID ID, which the latest azure-iot-sdk-c rejects as the ID is not a string.

By modifying the message ID slightly so it fails to parse as a UUID, azure-iot-sdk-c accepts the message without problem.

**Comment by pierreca** [comment] 2017-04-14 02:16
@peterdn good point - The `send` command might be affected, if using AMQP (wouldn't affect MQTT or HTTP). The `device-method` shouldn't though because device methods rely on MQTT. so it all depends if @kiranpradeep is using C2D messages (meaning the model in the serializer was declared with `WITH_ACTION`) or device methods (which i believe is tied to `WITH_DEVICE_METHOD` or `WITH_METHOD`. 

@zolvarga is looking into it and should be able to provide a more thorough answer.

**Comment by zolvarga** [comment] 2017-04-14 15:25
@kiranpradeep 

There is no code issue related to your problem. The calling convention for serializer is different.
Here is how you call the TurnFanOn method in serializer using iothub-explorer:
Iothub-explorer send z-001 {\"Name\":\"TurnFanOff\",\"Parameters\":\"{}\"}

The serializer takes the method name and the method parameters embedded in Json. (tha is the purpose of the serializer.)

If you want to use METHOD instead of ACTION you need to declare the function in the model model using WITH_METHOD macro and need to implement the device method callback handling. We don't have simplesample for that. We will create one and also add documentation into the samples how you would call them.

Best Regards,
Zoltan

**Comment by kiranpradeep** [comment] 2017-04-14 15:33
@pierreca Thanks for the pointer to WITH_METHOD([1](https://github.com/Azure/azure-iot-sdk-c/blob/2017-04-07/serializer/devdoc/serializer_apis.md#with_methodmethodname-arg1type-arg1-arg2type-arg2-)). I wasn't aware of it's existence. The Azure Serializer docs([2](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-device-sdk-c-serializer)) didn't mention it. I was using WITH_ACTION and hence the method wasn't getting invoked.

@zolvarga Thanks for the example using send messages. About sample, I see one inside a device twin!([3](https://github.com/Azure/azure-iot-sdk-c/blob/2017-04-07/serializer/samples/devicetwin_simplesample/devicetwin_simplesample.c#L50))

A one liner on when to choose between C2D messages(_ACTION) and direct methods(_METHODS) will help library users. Kindly ignore if it is already in docs.

**Comment by kiranpradeep** [comment] 2017-04-17 06:16
Even on forgetting serializer( the _ACTION vs _METHOD part ), the function `IoTHubClient_LL_SetMessageCallback` which is supposed to connect serializer and IotHub, is not invoking appropriate linking method. For e.g. in serializer mqtt sample([1](https://github.com/Azure/azure-iot-sdk-c/blob/2017-03-24/serializer/samples/simplesample_mqtt/simplesample_mqtt.c#L101)), the `IotHubMessage` function itself will not get invoked if I try `iothub-explorer device-method`. 

The connector function is correctly invoked if I try below as suggested by @zolvarga 
 `iothub-explorer send z-001 {"Name":"TurnFanOff","Parameters":"{}"}`

**Comment by zolvarga** [comment] 2017-04-17 17:26
@kiranpradeep 
Yes, that is the expected behavior. Serializer is working with the content of the payload Json to resolve actions, methods etc. 
I checked in a new sample for device method. It contains all the possible way to call a method on a device using serializer. Please take a look at it here:
https://github.com/Azure/azure-iot-sdk-c/tree/master/serializer/samples/devicemethod_simplesample

Best Regards,
Zoltan

**Closed** 2017-04-18 04:29 UTC
Labels: fix checked in, investigation-required
